### PR TITLE
Doesn't disable pinned tabs

### PR DESCRIPTION
**Pull request by cbonnissent**
Because some tabs need to be alive (chat, etc...)

### CODE REVIEW

**Comment by autonome** [comment]
Thanks for the PR!

I'd earlier noticed that pinned tabs are *not* being affected by the add-on (a good thing), but hadn't dug in to find out why.

Are you seeing pinned tabs put to sleep? I'm on Mac and they're definitely perma-alive in my case.

If you are, what OS and version are you on?

**Comment by cbonnissent** [comment]
Hello,

I'm on windows 10 and my rocket chat instance is pinned, with the extension my chat is put to sleep.

**Comment by passcod** [comment]
They were being kept alive until a few days ago, and now they're discarded like the rest. (I'm on Nightly.) That might be a recent change?

**Comment by passcod** [comment]
This is perhaps related to this: https://bugzilla.mozilla.org/show_bug.cgi?id=1415918

**Comment by passcod** [comment]
In any case, I think this PR is a good direction, to make "don't unload pinned tabs" explicit rather than relying on the browser's behaviour of `discard`.

**Comment by autonome** [comment]
THANKS!!

**Pull request merged**
